name: r0xCommands
version: 3
main: fr.Shayana.r0xCommands.r0xCommands
commands:
  tp:
    description: permet de se teleporter a un joueur, un joueur a un autre ou a une position
  tph:
    description: teleporte un joueur a vous
  put:
    description: teleporte un joueur a une position
  tpall:
    description: teleporte tous les joueurs a vous ou a un joueur
  accept:
    description: accepter une teleportation
  refuse:
    description: refuser une teleportation
  who:
    description: indique le nombre de joueurs sur le serveur ou d'un groupe
  suicide:
    description: si vous ne tenez plus a la vie
  kill:
    description: si vous n'aimez pas quelqu'un
  spawn:
    description: teleporte au spawn
  putspawn:
    description: teleporte un joueur au spawn
  home:
    description: teleporte au home
  give:
    description: donne a un joueur un item
  time:
    description: modifie le temps
  clear:
    description: nettoye son inventaire, ou celui d'un joueur
  me:
    description: message a la troiseme personne
  rules:
    description: affiche les regles
  whois:
    description: affiche des renseignements sur un joueur